"""Built-in UI strings and shared URLs for FL Lingo."""

from __future__ import annotations

from .localization import load_ui_translations

DISCORD_INVITE_URL = "https://discord.com/invite/RENtMMcc"
GITHUB_REPO_URL = "https://github.com/flathack/FL-Lingo"
GITHUB_LATEST_RELEASE_API = "https://api.github.com/repos/flathack/FL-Lingo/releases/latest"
GITHUB_LATEST_RELEASE_URL = "https://github.com/flathack/FL-Lingo/releases/latest"

STRINGS = {
    "de": {
        "status.start": "Aktuelles Spiel laden und dann gegen die Referenzinstallation vergleichen.",
        "group.installs": "Installationen",
        "group.workflow": "Arbeitsablauf",
        "group.main_actions": "Import / Export für externe Übersetzung",
        "group.apply_execution": "Übersetzungsdurchlauf",
        "group.filters": "Filter",
        "group.dll_analysis": "DLL-Analyse",
        "group.project": "Projektstatus",
        "group.progress": "Übersetzungsfortschritt",
        "mode.simple": "Simple Mode",
        "mode.expert": "Expertenmodus",
        "simple.group.paths": "Ordnerwahl",
        "simple.group.scan": "Scan",
        "simple.group.translate": "Übersetzen",
        "simple.label.mod_install": "Mod-Installation",
        "simple.label.reference_install": "Freelancer-Installation",
        "simple.paths.help": "Wähle links die Mod-Installation und die saubere Freelancer-Referenz.",
        "simple.scan.help": "Der Scan vergleicht beide Installationen und zeigt dir sofort, wie viel automatisch übersetzt werden kann.",
        "simple.translate.help": "Nach dem Scan kannst du die Übersetzung direkt in die Mod-Installation schreiben.",
        "simple.btn.scan": "Scan starten",
        "simple.summary.idle": "Wähle links beide Ordner. Danach scannt FL Lingo den Mod gegen die Referenzinstallation.",
        "simple.summary.source_loaded": "Quellinstallation geladen. Für den einfachen Ablauf fehlt noch der Vergleich mit der Referenzinstallation.",
        "simple.summary.ready": "{total} Einträge gescannt | {auto} automatisch | {manual} manuell | {open} offen | {dlls} DLLs betroffen",
        "simple.translate.idle": "Nach dem Scan kannst du hier die Übersetzung direkt anwenden.",
        "simple.translate.ready": "{count} Einträge können angewendet werden.",
        "simple.translate.resume": "Fortsetzung verfügbar: {done}/{total} DLLs abgeschlossen.",
        "simple.translate.no_toolchain": "Keine Resource-Toolchain gefunden.",
        "simple.audio_copy": "Audio auch kopieren",
        "simple.status": "Letzter Status: {message}",
        "label.source_install": "Spiel mit Mod / aktuelles Spiel",
        "label.target_install": "Referenzinstallation / Vergleichsspiel",
        "label.source_language": "Quellsprache",
        "label.target_language": "Zielsprache",
        "tooltip.source_language": "Sprache der Installation links.",
        "tooltip.target_language": "Sprache der Referenzinstallation rechts und der aktiven Terminologie.",
        "btn.browse": "Ordner...",
        "check.infocards": "Infocards einbeziehen",
        "btn.load_source": "Spiel laden",
        "btn.compare": "Mit Referenz vergleichen",
        "btn.export_visible": "Sichtbares JSON exportieren",
        "btn.export_mod_only": "Offene Einträge exportieren",
        "btn.export_long_open": "Lange offene Texte exportieren",
        "btn.import_exchange": "Übersetzung importieren",
        "btn.copy_audio": "Deutsche Audio kopieren",
        "btn.assemble_patch": "Patch zusammenstellen",
        "btn.apply_target": "Übersetzung durchführen",
        "btn.install_toolchain": "Toolchain installieren",
        "kind.all": "alle",
        "label.kind": "Typ",
        "label.status": "Status",
        "label.search": "Suche",
        "check.target_only": "Nur Einträge mit Zielreferenz",
        "check.changed_only": "Nur geänderte",
        "search.placeholder": "Suche in Quell- oder Zieltext",
        "table.units.kind": "Typ",
        "table.units.dll": "DLL",
        "table.units.local_id": "Local ID",
        "table.units.global_id": "Global ID",
        "table.units.status": "Status",
        "table.units.changed": "Geändert",
        "table.units.preview": "Vorschau aktuell",
        "table.units.old_text": "Alter Text",
        "table.plans.dll": "DLL",
        "table.plans.status": "Status",
        "table.plans.coverage": "Übersetzungsstand",
        "table.plans.ready": "Bereit",
        "table.plans.open": "Offen",
        "table.plans.reference": "Mit Referenz",
        "table.plans.action": "Vorgehen",
        "dll.legend": "Legende: Datei = betroffene Ressourcendatei | Status = wie gut diese DLL bereits über die Referenzsprache abgedeckt ist | Übersetzungsstand = bereits verfügbare oder anwendbare Einträge im Verhältnis zur Gesamtmenge | Bereit = schon in Zielsprache, automatisch übernehmbar oder manuell übersetzt | Offen = noch fehlende Einträge | Mit Referenz = Einträge mit Gegenstück in der Referenzinstallation | Vorgehen = was FL Lingo beim Anwenden mit dieser DLL macht.",
        "dll.tooltip.dll": "Name der betroffenen Ressourcen-DLL.",
        "dll.tooltip.status": "Einschätzung, ob diese DLL komplett abgedeckt, teilweise offen oder nur begrenzt automatisch nutzbar ist.",
        "dll.tooltip.coverage": "Anteil der Einträge, die schon verfügbar, automatisch übernehmbar oder manuell übersetzt sind.",
        "dll.tooltip.ready": "Einträge, die FL Lingo bereits direkt anwenden kann.",
        "dll.tooltip.open": "Einträge, die weiterhin offen sind und noch übersetzt werden müssen.",
        "dll.tooltip.reference": "Einträge mit passendem Gegenstück in der Referenzinstallation.",
        "dll.tooltip.action": "Die empfohlene Aktion für diese DLL beim Anwenden der Übersetzungen.",
        "preview.current": "Quelltext",
        "preview.reference": "Zieltext / Referenztext",
        "workflow.help": "Reihenfolge: 1. Aktuelles Spiel laden, 2. Referenzinstallation vergleichen, 3. Offene Einträge exportieren oder im Editor bearbeiten, 4. Übersetzungen anwenden.",
        "workflow.step1": "1. Spiel mit Mod / aktuelles Spiel wählen und laden",
        "workflow.step2": "2. Referenzinstallation / Vergleichsspiel wählen und vergleichen",
        "workflow.step3": "3. Offene Einträge direkt bearbeiten oder exportieren/importieren",
        "workflow.step4": "4. Vorschau prüfen und Übersetzungen anwenden",
        "tab.start": "Startseite",
        "tab.main": "Hauptworkflow",
        "tab.workspace": "Bearbeitung",
        "tab.editor": "Offene Übersetzungen",
        "tab.dlls": "DLL-Analyse",
        "tab.terminology": "Terminologie",
        "main.help": "Hauptworkflow für FL Lingo: offene Einträge exportieren, extern übersetzen, Übersetzung importieren, danach Vorschau prüfen und anwenden.",
        "main.step.export": "A. Offene Einträge exportieren",
        "main.step.import": "B. Übersetzung importieren",
        "main.step.apply": "C. Übersetzungen anwenden",
        "main.note": "Der manuelle Editor ist optional und liegt im separaten Tab 'Editor'.",
        "editor.help": "Hier werden standardmäßig nur fehlende Übersetzungen angezeigt. Bereits übersetzte Einträge kannst du über die Filter wieder einblenden.",
        "editor.missing": "Fehlende Übersetzungen: {count}",
        "editor.missing_detail": "Offene Einträge ohne manuelle Übersetzung: {count}",
        "editor.old_text_source": "Alter Text aus",
        "editor.old_text_current": "Aktueller Stand",
        "group.terminology_map": "Terminologie-Mapping",
        "group.terminology_manage": "Terminologie und Pattern-Verwaltung",
        "label.term_source": "Quellbegriff",
        "label.term_target": "Zielbegriff",
        "label.pattern_source": "Pattern Quelle",
        "label.pattern_target": "Pattern Ziel",
        "btn.term_from_selection": "Aus Auswahl übernehmen",
        "btn.term_save": "Mapping speichern",
        "btn.pattern_save": "Pattern speichern",
        "btn.terminology_reload": "Listen neu laden",
        "table.terms.section": "Bereich",
        "table.terms.source": "Quelle",
        "table.terms.target": "Ziel",
        "table.patterns.section": "Bereich",
        "table.patterns.source": "Pattern",
        "table.patterns.target": "Ersetzung",
        "preview.edit_hint": "Direkt editierbar für manuelle Übersetzungen oder Korrekturen.",
        "btn.save_edit": "Änderung speichern",
        "btn.reset_edit": "Manuelle Änderung zurücksetzen",
        "toolchain.available": "verfügbar",
        "toolchain.unavailable": "nicht verfügbar",
        "detail.none": "Keine Auswahl.",
        "summary.none": "Noch kein Katalog geladen.",
        "project.none": "Kein Projekt geladen",
        "project.info": "{name} | {dirty}",
        "progress.none": "Noch kein Katalog geladen.",
        "progress.text": "{percent}% | {done}/{total} Einträge abgedeckt | {localized} bereits im Spiel übersetzt | {available} sofort anwendbar | {skipped} übersprungen",
        "progress.legend": "Lila = bereits im Spiel übersetzt | Grün = sofort anwendbar | Gelb = bewusst übersprungen",
        "progress.audio.none": "Noch keine Audio-Referenz geladen.",
        "progress.audio.text": "Audio {percent}% | {ready}/{total} deutsche Voice-Dateien passend | {open} offen",
        "apply.run.idle": "Bereit. Noch keine laufende Übersetzung.",
        "apply.run.resume_available": "Fortsetzung verfügbar: {done}/{total} DLLs abgeschlossen.",
        "apply.run.running": "Laufend: {done}/{total} DLLs abgeschlossen.",
        "apply.run.completed": "Abgeschlossen: {done}/{total} DLLs verarbeitet.",
        "apply.run.failed": "Abgebrochen bei {dll}. Fortschritt wurde gespeichert und kann später fortgesetzt werden.",
        "apply.run.current_dll": "Aktuelle DLL: {dll} ({action})",
        "apply.run.current_lines": "Aktuelle Einträge:\n{lines}",
        "apply.run.copy": "vollstaendig patchen",
        "apply.run.patch": "patchen",
        "apply.run.none": "Noch keine Einträge aktiv.",
        "project.saved": "gespeichert",
        "project.unsaved": "nicht gespeichert",
        "plan.action.full": "alle passenden Eintraege patchen",
        "plan.action.patch": "fertige Einträge anwenden",
        "plan.action.unsafe": "manuell prüfen",
        "plan.strategy.full": "Komplett mit Referenz abgedeckt",
        "plan.strategy.patch": "Teilweise abgedeckt, Rest offen",
        "plan.strategy.unsafe": "Nur begrenzt automatisch nutzbar",
        "menu.file": "Datei",
        "menu.view": "Ansicht",
        "menu.settings": "Einstellungen",
        "menu.help": "Hilfe",
        "menu.language": "Language",
        "menuitem.focus_dll": "DLL-Analyse fokussieren",
        "menuitem.focus_units": "Eintragsliste fokussieren",
        "menuitem.appearance": "Darstellung...",
        "menuitem.open_terminology": "Terminologie öffnen...",
        "menuitem.term_source_from_selection": "Auswahl als Quellbegriff verwenden",
        "menuitem.term_target_from_selection": "Auswahl als Zielbegriff verwenden",
        "menuitem.term_save_from_selection": "Mapping für Auswahl speichern",
        "menuitem.check_updates": "Auf Updates prüfen...",
        "menuitem.help_contents": "Hilfe öffnen...",
        "menuitem.about": "Über",
        "menuitem.project_load": "Projekt laden...",
        "menuitem.project_new": "Neues Projekt",
        "menuitem.project_rebuild": "Projekt neu aufbauen",
        "menuitem.project_save": "Projekt speichern...",
        "menuitem.project_save_as": "Projekt speichern unter...",
        "menuitem.restore_backup": "Backup wiederherstellen...",
        "menuitem.file_assoc": ".FLLingo verknüpfen...",
        "menuitem.copy_audio": "Deutsche Audio kopieren...",
        "menuitem.assemble_patch": "Patch zusammenstellen...",
        "status.loaded_source": "Quellinstallation geladen: {path}",
        "status.loaded_compare": "Referenz geladen: {path}",
        "status.project_saved": "Projekt gespeichert: {path}",
        "status.project_loaded": "Projekt geladen: {path}",
        "status.project_new": "Neues Projekt gestartet.",
        "status.project_rebuilt": "Projekt neu aufgebaut.",
        "status.settings_applied": "Einstellungen angewendet.",
        "status.language_changed": "Sprache gewechselt.",
        "status.toolchain_started": "Toolchain-Installer gestartet.",
        "status.terminology_opened": "Terminologie geöffnet: {path}",
        "status.terminology_saved": "Terminologie-Mapping gespeichert: {source} -> {target}",
        "status.pattern_saved": "Pattern gespeichert: {source} -> {target}",
        "status.term_source_selected": "Quellbegriff aus Auswahl übernommen.",
        "status.term_target_selected": "Zielbegriff aus Auswahl übernommen.",
        "status.audio_copied": "{count} deutsche Voice-Dateien kopiert.",
        "status.patch_assembled": "Patch zusammengestellt: {path}",
        "status.update_check_started": "Update-Prüfung gestartet.",
        "status.operation_failed": "Vorgang fehlgeschlagen.",
        "error.source_missing": "Quellpfad existiert nicht:\n{path}",
        "error.load_source_failed": "Quellinstallation konnte nicht geladen werden:\n{error}",
        "error.target_missing": "Pfad der Referenzinstallation existiert nicht:\n{path}",
        "error.compare_failed": "Vergleich mit der Referenzinstallation fehlgeschlagen:\n{error}",
        "error.load_first": "Bitte zuerst eine Installation laden.",
        "error.compare_first": "Bitte zuerst mit der Referenzinstallation vergleichen.",
        "error.toolchain_missing": "Keine Resource-Toolchain gefunden.\nBitte zuerst 'Toolchain installieren' ausführen.",
        "tooltip.apply_disabled_toolchain": "Es wurde keine unterstützte Resource-Toolchain gefunden. Installiere LLVM-Tools oder setze FLATLAS_TOOLCHAIN_DIR.",
        "tooltip.apply_disabled_compare": "Lade zuerst ein aktuelles Spiel und eine Referenzinstallation, damit die Übersetzung angewendet werden kann.",
        "error.no_apply_units": "Im aktuellen Projekt gibt es keine automatisch oder manuell anwendbaren Einträge.",
        "error.export_failed": "JSON-Export fehlgeschlagen:\n{error}",
        "error.export_mod_only_failed": "Export offener Einträge fehlgeschlagen:\n{error}",
        "error.import_failed": "Import fehlgeschlagen:\n{error}",
        "error.apply_failed": "Übersetzungen konnten nicht angewendet werden:\n{error}",
        "error.toolchain_start_failed": "Toolchain-Installer konnte nicht gestartet werden:\n{error}",
        "error.project_save_failed": "Projekt konnte nicht gespeichert werden:\n{error}",
        "error.project_load_failed": "Projekt konnte nicht geladen werden:\n{error}",
        "error.file_assoc_failed": "Dateizuordnung konnte nicht eingerichtet werden:\n{error}",
        "error.terminology_open_failed": "Terminologie-Datei konnte nicht geöffnet werden:\n{error}",
        "error.term_mapping_empty": "Quell- und Zielbegriff müssen ausgefüllt sein.",
        "error.pattern_mapping_empty": "Pattern-Quelle und Pattern-Ziel müssen ausgefüllt sein.",
        "error.term_mapping_save_failed": "Terminologie-Mapping konnte nicht gespeichert werden:\n{error}",
        "error.pattern_mapping_save_failed": "Pattern konnte nicht gespeichert werden:\n{error}",
        "error.update_check_failed": "Update-Prüfung fehlgeschlagen:\n{error}",
        "error.audio_copy_failed": "Audio-Kopie fehlgeschlagen:\n{error}",
        "error.patch_assemble_failed": "Patch konnte nicht zusammengestellt werden:\n{error}",
        "error.no_audio_candidates": "Keine abweichenden deutschen Voice-Dateien gefunden.",
        "error.no_patch_files": "Keine Dateien für den Patch gefunden.",
        "dialog.export_visible": "Sichtbaren Datensatz exportieren",
        "dialog.project_save": "Projekt speichern",
        "dialog.project_save_as": "Projekt speichern unter",
        "dialog.progress_title": "Bitte warten",
        "progress.load_source": "Spielinstallation wird geladen...",
        "progress.compare": "Referenzinstallation wird verglichen...",
        "progress.export_visible": "Sichtbare Einträge werden exportiert...",
        "progress.export_open": "Offene Einträge werden exportiert...",
        "progress.export_long_open": "Lange offene Texte werden exportiert...",
        "progress.import_translation": "Übersetzungsdatei wird importiert...",
        "progress.copy_audio": "Deutsche Audio werden kopiert...",
        "progress.assemble_patch": "Patch wird zusammengestellt...",
        "progress.save_project": "Projekt wird gespeichert...",
        "progress.load_project": "Projekt wird geladen...",
        "dialog.project_load": "Projekt laden",
        "dialog.file_assoc": ".FLLingo verknüpfen",
        "dialog.file_assoc_done": "Dateizuordnung eingerichtet.\n\n{path}",
        "dialog.unsaved_title": "Ungespeicherte Änderungen",
        "dialog.unsaved_message": "Es gibt ungespeicherte Änderungen im aktuellen Projekt.\n\nVor dem Fortfahren speichern?",
        "dialog.rebuild_title": "Projekt neu aufbauen",
        "dialog.rebuild_message": "Das Projekt wird nur aus den aktuellen Spieldaten neu aufgebaut.\n\nManuelle Übersetzungen, importierte Änderungen und andere nicht aus dem Spiel geladene Projektanpassungen gehen dabei verloren.\n\nFortfahren?",
        "dialog.apply_title": "Übersetzungen anwenden",
        "dialog.apply_confirm": "Es werden {count} Einträge ersetzt. Vorher wird ein Backup angelegt.\n\nAbdeckung aktuell: {covered_percent}% ({covered}/{total} Einträge sind bereits lila, grün oder gelb)\n\nFortfahren?",
        "dialog.apply_confirm_resume": "Es werden {count} Einträge ersetzt. Vorher wird ein Backup angelegt oder eine vorhandene Sitzung fortgesetzt.\n\nAbdeckung aktuell: {covered_percent}% ({covered}/{total} Einträge sind bereits lila, grün oder gelb)\n\nEs kann bei DLL {next_dll} weitergemacht werden. Bereits fertig: {done}/{dll_total} DLLs.\n\nFortfahren?",
        "dialog.apply_preview": "Anwenden-Vorschau",
        "dialog.apply_progress_title": "Übersetzungen anwenden",
        "dialog.apply_progress_copy": "Bearbeite {current}/{total}: {dll} wird komplett ersetzt...",
        "dialog.apply_progress_patch": "Bearbeite {current}/{total}: {dll} wird gepatcht...",
        "dialog.restore_backup": "Backup wiederherstellen",
        "dialog.restore_confirm": "Backup wiederherstellen und aktuelle DLLs überschreiben?\n\n{path}",
        "dialog.apply_success": "Übersetzungen abgeschlossen.\n\nErsetzte Einträge: {count}\nGeschriebene DLLs: {dlls}\nBackup: {backup}",
        "dialog.restore_success": "Backup wiederhergestellt.\n\nDLLs: {count}\nQuelle: {path}",
        "dialog.copy_audio_title": "Deutsche Audio kopieren",
        "dialog.copy_audio_offer": "{count} abweichende deutsche Voice-Dateien wurden gefunden.\n\nDiese jetzt aus der Referenzinstallation in die Mod-Installation kopieren?\n\nBackup: {backup}",
        "dialog.copy_audio_success": "Audio-Kopie abgeschlossen.\n\nKopierte Dateien: {count}\nBackup: {backup}",
        "dialog.assemble_patch_title": "Patch zusammenstellen",
        "dialog.assemble_patch_include_audio": "{count} abweichende deutsche Voice-Dateien wurden gefunden.\n\nSollen diese zusätzlich in den Patch aufgenommen werden?",
        "dialog.assemble_patch_success": "Patch zusammengestellt.\n\nDateien: {count}\nOrdner: {path}\nManifest: {manifest}",
        "dialog.toolchain_title": "Toolchain installieren",
        "dialog.toolchain_started": "Installer gestartet:\n{path}",
        "dialog.about.title": "Über FL Lingo",
        "dialog.about.body": "<h2>FL Lingo</h2><p>Ein Relocalization-Tool für Freelancer-Mods. Es vergleicht eine modifizierte Installation mit einer Referenzinstallation, stellt bekannte Texte automatisch wieder her und unterstützt den Export/Import für externe Übersetzungen.</p><p><b>Version:</b> {version}<br><b>{developed_by}</b></p><p><a href=\"{github}\">GitHub Repository</a><br><a href=\"{discord}\">Discord Server</a></p>",
        "dialog.help.title": "FL Lingo Hilfe",
        "error.help_open_failed": "Die Hilfe-Datei konnte nicht geladen werden:\n{error}",
        "footer.html": "{developed_by} - Version {version} - <a href=\"{discord}\">Discord Server</a> - <a href=\"{github}\">GitHub Repository</a>",
        "updates.title": "Updates",
        "updates.up_to_date": "FL Lingo ist aktuell. Installierte Version: {version}",
        "updates.available": "Ein Update ist verfügbar.\n\nInstalliert: {current}\nNeu: {latest}",
        "updates.available_info": "Möchtest du die Release-Seite auf GitHub öffnen?",
        "updates.open_release": "Release öffnen",
        "updates.version_parse_failed": "Die Release-Version konnte nicht ausgewertet werden.",
        "status.manual_saved": "Manuelle Übersetzung gespeichert.",
        "status.manual_reset": "Manuelle Übersetzung zurückgesetzt.",
        "status.backup_restored": "Backup wiederhergestellt: {path}",
        "status.file_assoc_done": ".FLLingo verknüpft.",
        "error.select_entry": "Bitte zuerst einen Eintrag auswählen.",
        "error.no_backups": "Keine Backups für diese Installation gefunden.",
        "error.restore_failed": "Backup konnte nicht wiederhergestellt werden:\n{error}",
        "summary.visible": "Sichtbar {visible}/{total}",
        "summary.full": "DLL komplett ersetzbar {count}",
        "summary.patch": "DLL teilweise {count}",
        "summary.unsafe": "DLL unsicher {count}",
        "summary.strings": "Strings auto {auto}, manuell {manual}, schon Ziel {localized}, mod-only {mod_only}",
        "summary.infocards": "Infocards auto {auto}, manuell {manual}, schon Ziel {localized}, mod-only {mod_only}",
        "detail.kind": "Typ",
        "detail.status": "Status",
        "detail.reference": "Zielreferenz",
        "detail.manual": "Manuell",
        "detail.changed": "Geändert",
        "status.auto_relocalize": "Automatisch übernehmbar",
        "status.already_localized": "Bereits in Zielsprache",
        "status.manual_translation": "Manuell übersetzt",
        "status.mod_only": "Nur Mod-Inhalt",
        "status.export_mod_only": "{exported} offene Einträge exportiert | {skipped} übersprungen | Glossar {glossary}",
        "status.export_long_open": "{exported} lange offene Texte exportiert | {skipped} übersprungen | Glossar {glossary}",
        "error.export_long_open_failed": "Export langer offener Texte fehlgeschlagen:\n{error}",
        "yes": "ja",
        "no": "nein",
    },
    "en": {
        "status.start": "Load the current game and compare it against the reference install.",
        "group.installs": "Installs",
        "group.workflow": "Workflow",
        "group.main_actions": "Import / Export for External Translation",
        "group.apply_execution": "Translation Run",
        "group.filters": "Filters",
        "group.dll_analysis": "DLL Analysis",
        "group.project": "Project Status",
        "group.progress": "Translation Progress",
        "mode.simple": "Simple Mode",
        "mode.expert": "Expert Mode",
        "simple.group.paths": "Folder Selection",
        "simple.group.scan": "Scan",
        "simple.group.translate": "Translate",
        "simple.label.mod_install": "Mod install",
        "simple.label.reference_install": "Freelancer install",
        "simple.paths.help": "Choose the mod install and the clean Freelancer reference on the left.",
        "simple.scan.help": "The scan compares both installs and immediately shows how much can be translated automatically.",
        "simple.translate.help": "After the scan you can write the translation directly into the mod install.",
        "simple.btn.scan": "Start scan",
        "simple.summary.idle": "Choose both folders on the left. FL Lingo will then scan the mod against the reference install.",
        "simple.summary.source_loaded": "Source install loaded. The simplified workflow still needs the reference comparison.",
        "simple.summary.ready": "{total} entries scanned | {auto} automatic | {manual} manual | {open} open | {dlls} DLLs affected",
        "simple.translate.idle": "After the scan you can apply the translation directly here.",
        "simple.translate.ready": "{count} entries can be applied.",
        "simple.translate.resume": "Resume available: {done}/{total} DLLs completed.",
        "simple.translate.no_toolchain": "No resource toolchain found.",
        "simple.audio_copy": "Copy audio too",
        "simple.status": "Last status: {message}",
        "label.source_install": "Game with mod / current game",
        "label.target_install": "Reference install / comparison game",
        "label.source_language": "Source language",
        "label.target_language": "Target language",
        "tooltip.source_language": "Language of the install on the left.",
        "tooltip.target_language": "Language of the reference install on the right and the active terminology.",
        "btn.browse": "Browse...",
        "check.infocards": "Include infocards",
        "btn.load_source": "Load game",
        "btn.compare": "Compare with reference",
        "btn.export_visible": "Export visible JSON",
        "btn.export_mod_only": "Export open entries",
        "btn.export_long_open": "Export long open texts",
        "btn.import_exchange": "Import translation",
        "btn.copy_audio": "Copy German audio",
        "btn.assemble_patch": "Assemble patch",
        "btn.apply_target": "Run translation",
        "btn.install_toolchain": "Install toolchain",
        "kind.all": "all",
        "label.kind": "Kind",
        "label.status": "Status",
        "label.search": "Search",
        "check.target_only": "Only entries with target reference",
        "check.changed_only": "Changed only",
        "search.placeholder": "Search in source or target text",
        "table.units.kind": "Kind",
        "table.units.dll": "DLL",
        "table.units.local_id": "Local ID",
        "table.units.global_id": "Global ID",
        "table.units.status": "Status",
        "table.units.changed": "Changed",
        "table.units.preview": "Current preview",
        "table.units.old_text": "Old text",
        "table.plans.dll": "DLL",
        "table.plans.status": "Status",
        "table.plans.coverage": "Coverage",
        "table.plans.ready": "Ready",
        "table.plans.open": "Open",
        "table.plans.reference": "With reference",
        "table.plans.action": "Action",
        "dll.legend": "Legend: File = affected resource DLL | Status = how well the DLL is already covered by the reference language | Coverage = ready entries compared to all entries in that DLL | Ready = already in target language, auto-transferable, or manually translated | Open = entries still missing a translation | With reference = entries with a matching counterpart in the reference install | Action = what FL Lingo will do with this DLL when applying changes.",
        "dll.tooltip.dll": "Name of the affected resource DLL.",
        "dll.tooltip.status": "Assessment of whether this DLL is fully covered, partially open, or only limited in what can be applied automatically.",
        "dll.tooltip.coverage": "Share of entries already available, auto-transferable, or manually translated.",
        "dll.tooltip.ready": "Entries FL Lingo can already apply directly.",
        "dll.tooltip.open": "Entries still missing a translation.",
        "dll.tooltip.reference": "Entries with a matching counterpart in the reference install.",
        "dll.tooltip.action": "The recommended action FL Lingo will perform for this DLL.",
        "preview.current": "Source text",
        "preview.reference": "Target / reference text",
        "workflow.help": "Recommended order: 1. Load the current game, 2. Compare with the reference install, 3. Edit open entries directly or export/import them, 4. Review preview and apply translations.",
        "workflow.step1": "1. Choose and load the game with mod / current game",
        "workflow.step2": "2. Choose the reference install / comparison game and compare",
        "workflow.step3": "3. Edit open entries directly or use export/import",
        "workflow.step4": "4. Review the preview and apply translations",
        "tab.start": "Start Page",
        "tab.main": "Main Workflow",
        "tab.workspace": "Editing",
        "tab.editor": "Open Translations",
        "tab.dlls": "DLL Analysis",
        "tab.terminology": "Terminology",
        "main.help": "Primary FL Lingo workflow: export open entries, translate externally, import the translation, then review and apply.",
        "main.step.export": "A. Export open entries",
        "main.step.import": "B. Import translation",
        "main.step.apply": "C. Apply translations",
        "main.note": "The manual editor is optional and lives in the separate 'Editor' tab.",
        "editor.help": "This tab defaults to missing translations only. You can bring translated entries back with the filters.",
        "editor.missing": "Missing translations: {count}",
        "editor.missing_detail": "Open entries without manual translation: {count}",
        "editor.old_text_source": "Old text from",
        "editor.old_text_current": "Current install",
        "group.terminology_map": "Terminology Mapping",
        "group.terminology_manage": "Terminology and Pattern Management",
        "label.term_source": "Source term",
        "label.term_target": "Target term",
        "label.pattern_source": "Pattern source",
        "label.pattern_target": "Pattern target",
        "btn.term_from_selection": "Use selection",
        "btn.term_save": "Save mapping",
        "btn.pattern_save": "Save pattern",
        "btn.terminology_reload": "Reload lists",
        "table.terms.section": "Section",
        "table.terms.source": "Source",
        "table.terms.target": "Target",
        "table.patterns.section": "Section",
        "table.patterns.source": "Pattern",
        "table.patterns.target": "Replacement",
        "preview.edit_hint": "Directly editable for manual translations or corrections.",
        "btn.save_edit": "Save edit",
        "btn.reset_edit": "Reset manual edit",
        "toolchain.available": "available",
        "toolchain.unavailable": "not available",
        "detail.none": "No selection.",
        "summary.none": "No catalog loaded.",
        "project.none": "No project loaded",
        "project.info": "{name} | {dirty}",
        "progress.none": "No catalog loaded yet.",
        "progress.text": "{percent}% | {done}/{total} entries covered | {localized} already translated in-game | {available} ready to apply | {skipped} skipped",
        "progress.legend": "Purple = already translated in-game | Green = ready to apply | Yellow = intentionally skipped",
        "progress.audio.none": "No audio reference loaded yet.",
        "progress.audio.text": "Audio {percent}% | {ready}/{total} German voice files match | {open} open",
        "apply.run.idle": "Ready. No translation run is active.",
        "apply.run.resume_available": "Resume available: {done}/{total} DLLs already completed.",
        "apply.run.running": "Running: {done}/{total} DLLs completed.",
        "apply.run.completed": "Completed: {done}/{total} DLLs processed.",
        "apply.run.failed": "Stopped at {dll}. Progress was saved and can be resumed later.",
        "apply.run.current_dll": "Current DLL: {dll} ({action})",
        "apply.run.current_lines": "Current entries:\n{lines}",
        "apply.run.copy": "full patch",
        "apply.run.patch": "patch",
        "apply.run.none": "No active entries yet.",
        "project.saved": "saved",
        "project.unsaved": "unsaved",
        "plan.action.full": "patch all matched entries",
        "plan.action.patch": "apply ready entries",
        "plan.action.unsafe": "review manually",
        "plan.strategy.full": "Fully covered by reference",
        "plan.strategy.patch": "Partially covered, some open",
        "plan.strategy.unsafe": "Limited automatic coverage",
        "menu.file": "File",
        "menu.view": "View",
        "menu.settings": "Settings",
        "menu.help": "Help",
        "menu.language": "Language",
        "menuitem.focus_dll": "Focus DLL analysis",
        "menuitem.focus_units": "Focus entries",
        "menuitem.appearance": "Appearance...",
        "menuitem.open_terminology": "Open terminology...",
        "menuitem.term_source_from_selection": "Use selection as source term",
        "menuitem.term_target_from_selection": "Use selection as target term",
        "menuitem.term_save_from_selection": "Save mapping for selection",
        "menuitem.check_updates": "Check for updates...",
        "menuitem.help_contents": "Open help...",
        "menuitem.about": "About",
        "menuitem.project_load": "Load project...",
        "menuitem.project_new": "New project",
        "menuitem.project_rebuild": "Rebuild project",
        "menuitem.project_save": "Save project...",
        "menuitem.project_save_as": "Save project as...",
        "menuitem.restore_backup": "Restore backup...",
        "menuitem.file_assoc": "Associate .FLLingo...",
        "menuitem.copy_audio": "Copy German audio...",
        "menuitem.assemble_patch": "Assemble patch...",
        "status.loaded_source": "Loaded source install: {path}",
        "status.loaded_compare": "Loaded reference install: {path}",
        "status.project_saved": "Project saved: {path}",
        "status.project_loaded": "Project loaded: {path}",
        "status.project_new": "Started a new project.",
        "status.project_rebuilt": "Project rebuilt.",
        "status.settings_applied": "Settings applied.",
        "status.language_changed": "Language changed.",
        "status.toolchain_started": "Toolchain installer started.",
        "status.terminology_opened": "Opened terminology: {path}",
        "status.terminology_saved": "Terminology mapping saved: {source} -> {target}",
        "status.pattern_saved": "Pattern saved: {source} -> {target}",
        "status.term_source_selected": "Source term copied from selection.",
        "status.term_target_selected": "Target term copied from selection.",
        "status.audio_copied": "Copied {count} German voice files.",
        "status.patch_assembled": "Patch assembled: {path}",
        "status.update_check_started": "Started update check.",
        "status.operation_failed": "Operation failed.",
        "error.source_missing": "Source path does not exist:\n{path}",
        "error.load_source_failed": "Source install could not be loaded:\n{error}",
        "error.target_missing": "Reference install path does not exist:\n{path}",
        "error.compare_failed": "Comparison with reference install failed:\n{error}",
        "error.load_first": "Load an install first.",
        "error.compare_first": "Compare against the reference install first.",
        "error.toolchain_missing": "No resource toolchain found.\nRun 'Install toolchain' first.",
        "tooltip.apply_disabled_toolchain": "No supported resource toolchain was found. Install LLVM tools or set FLATLAS_TOOLCHAIN_DIR.",
        "tooltip.apply_disabled_compare": "Load a current game and a reference install first so translations can be applied.",
        "error.no_apply_units": "There are no automatically or manually applicable entries in the current project.",
        "error.export_failed": "JSON export failed:\n{error}",
        "error.export_mod_only_failed": "Open entry export failed:\n{error}",
        "error.import_failed": "Import failed:\n{error}",
        "error.apply_failed": "Applying translations failed:\n{error}",
        "error.toolchain_start_failed": "Toolchain installer could not be started:\n{error}",
        "error.project_save_failed": "Project could not be saved:\n{error}",
        "error.project_load_failed": "Project could not be loaded:\n{error}",
        "error.file_assoc_failed": "File association could not be configured:\n{error}",
        "error.terminology_open_failed": "Terminology file could not be opened:\n{error}",
        "error.term_mapping_empty": "Source term and target term must be filled in.",
        "error.pattern_mapping_empty": "Pattern source and target must be filled in.",
        "error.term_mapping_save_failed": "Terminology mapping could not be saved:\n{error}",
        "error.pattern_mapping_save_failed": "Pattern could not be saved:\n{error}",
        "error.update_check_failed": "Update check failed:\n{error}",
        "error.audio_copy_failed": "Audio copy failed:\n{error}",
        "error.patch_assemble_failed": "Patch assembly failed:\n{error}",
        "error.no_audio_candidates": "No differing German voice files were found.",
        "error.no_patch_files": "No files were found for patch assembly.",
        "dialog.export_visible": "Export visible dataset",
        "dialog.project_save": "Save project",
        "dialog.project_save_as": "Save project as",
        "dialog.progress_title": "Please wait",
        "progress.load_source": "Loading game install...",
        "progress.compare": "Comparing reference install...",
        "progress.export_visible": "Exporting visible entries...",
        "progress.export_open": "Exporting open entries...",
        "progress.export_long_open": "Exporting long open texts...",
        "progress.import_translation": "Importing translation file...",
        "progress.copy_audio": "Copying German audio...",
        "progress.assemble_patch": "Assembling patch...",
        "progress.save_project": "Saving project...",
        "progress.load_project": "Loading project...",
        "dialog.project_load": "Load project",
        "dialog.file_assoc": "Associate .FLLingo",
        "dialog.file_assoc_done": "File association configured.\n\n{path}",
        "dialog.unsaved_title": "Unsaved changes",
        "dialog.unsaved_message": "There are unsaved changes in the current project.\n\nSave before continuing?",
        "dialog.rebuild_title": "Rebuild project",
        "dialog.rebuild_message": "The project will be rebuilt only from the current game data.\n\nManual translations, imported changes, and other project edits that do not come from the game data will be lost.\n\nContinue?",
        "dialog.apply_title": "Apply translations",
        "dialog.apply_confirm": "{count} entries will be replaced. A backup is created first.\n\nCurrent coverage: {covered_percent}% ({covered}/{total} entries are already purple, green, or yellow)\n\nContinue?",
        "dialog.apply_confirm_resume": "{count} entries will be replaced. A backup is created first or an existing session will be resumed.\n\nCurrent coverage: {covered_percent}% ({covered}/{total} entries are already purple, green, or yellow)\n\nIt can continue at DLL {next_dll}. Already completed: {done}/{dll_total} DLLs.\n\nContinue?",
        "dialog.apply_preview": "Apply preview",
        "dialog.apply_progress_title": "Apply translations",
        "dialog.apply_progress_copy": "Processing {current}/{total}: replacing {dll}...",
        "dialog.apply_progress_patch": "Processing {current}/{total}: patching {dll}...",
        "dialog.restore_backup": "Restore backup",
        "dialog.restore_confirm": "Restore this backup and overwrite current DLLs?\n\n{path}",
        "dialog.apply_success": "Translations finished.\n\nReplaced entries: {count}\nWritten DLLs: {dlls}\nBackup: {backup}",
        "dialog.restore_success": "Backup restored.\n\nDLLs: {count}\nSource: {path}",
        "dialog.copy_audio_title": "Copy German audio",
        "dialog.copy_audio_offer": "{count} differing German voice files were found.\n\nCopy them now from the reference install into the mod install?\n\nBackup: {backup}",
        "dialog.copy_audio_success": "Audio copy finished.\n\nCopied files: {count}\nBackup: {backup}",
        "dialog.assemble_patch_title": "Assemble patch",
        "dialog.assemble_patch_include_audio": "{count} differing German voice files were found.\n\nInclude them in the patch as well?",
        "dialog.assemble_patch_success": "Patch assembled.\n\nFiles: {count}\nFolder: {path}\nManifest: {manifest}",
        "dialog.toolchain_title": "Install toolchain",
        "dialog.toolchain_started": "Installer started:\n{path}",
        "dialog.about.title": "About FL Lingo",
        "dialog.about.body": "<h2>FL Lingo</h2><p>A relocalization tool for Freelancer mods. It compares a modded game install with a reference install, restores known text automatically, and supports export/import for external translation workflows.</p><p><b>Version:</b> {version}<br><b>{developed_by}</b></p><p><a href=\"{github}\">GitHub Repository</a><br><a href=\"{discord}\">Discord Server</a></p>",
        "dialog.help.title": "FL Lingo Help",
        "error.help_open_failed": "The help file could not be loaded:\n{error}",
        "footer.html": "{developed_by} - Version {version} - <a href=\"{discord}\">Join Discord Server</a> - <a href=\"{github}\">GitHub Repository</a>",
        "updates.title": "Updates",
        "updates.up_to_date": "FL Lingo is up to date. Installed version: {version}",
        "updates.available": "An update is available.\n\nInstalled: {current}\nLatest: {latest}",
        "updates.available_info": "Do you want to open the release page on GitHub?",
        "updates.open_release": "Open release",
        "updates.version_parse_failed": "The release version could not be parsed.",
        "status.manual_saved": "Manual translation saved.",
        "status.manual_reset": "Manual translation reset.",
        "status.backup_restored": "Backup restored: {path}",
        "status.file_assoc_done": ".FLLingo associated.",
        "error.select_entry": "Select an entry first.",
        "error.no_backups": "No backups found for this install.",
        "error.restore_failed": "Backup could not be restored:\n{error}",
        "summary.visible": "Visible {visible}/{total}",
        "summary.full": "DLL full replace {count}",
        "summary.patch": "DLL partial {count}",
        "summary.unsafe": "DLL unsafe {count}",
        "summary.strings": "Strings auto {auto}, manual {manual}, already target {localized}, mod-only {mod_only}",
        "summary.infocards": "Infocards auto {auto}, manual {manual}, already target {localized}, mod-only {mod_only}",
        "detail.kind": "Kind",
        "detail.status": "Status",
        "detail.reference": "Target reference",
        "detail.manual": "Manual",
        "detail.changed": "Changed",
        "status.auto_relocalize": "Auto transferable",
        "status.already_localized": "Already in target language",
        "status.manual_translation": "Manually translated",
        "status.mod_only": "Mod-only content",
        "status.export_mod_only": "{exported} open entries exported | {skipped} skipped | glossary {glossary}",
        "status.export_long_open": "{exported} long open texts exported | {skipped} skipped | glossary {glossary}",
        "error.export_long_open_failed": "Long open text export failed:\n{error}",
        "yes": "yes",
        "no": "no",
    },
}

STRINGS["fr"] = dict(STRINGS["en"]) | {
    "group.installs": "Installations",
    "group.workflow": "Flux",
    "group.main_actions": "Flux Principal",
    "group.filters": "Filtres",
    "group.dll_analysis": "Analyse DLL",
    "group.project": "Etat du Projet",
    "group.progress": "Progression de Traduction",
    "label.source_install": "Jeu actuel / jeu avec mod",
    "label.target_install": "Installation de reference / jeu de comparaison",
    "label.source_language": "Langue source",
    "label.target_language": "Langue cible",
    "btn.browse": "Parcourir...",
    "btn.load_source": "Charger le jeu",
    "btn.compare": "Comparer avec la reference",
    "btn.import_exchange": "Importer la traduction",
    "btn.apply_target": "Appliquer les traductions",
    "menu.file": "Fichier",
    "menu.view": "Affichage",
    "menu.settings": "Parametres",
    "menu.help": "Aide",
    "menuitem.project_load": "Charger le projet...",
    "menuitem.project_new": "Nouveau projet",
    "menuitem.project_save": "Enregistrer le projet...",
    "menuitem.open_terminology": "Ouvrir la terminologie...",
    "menuitem.check_updates": "Verifier les mises a jour...",
    "menuitem.about": "A propos",
    "status.language_changed": "Langue changee.",
    "updates.title": "Mises a jour",
    "updates.up_to_date": "FL Lingo est a jour. Version installee : {version}",
    "updates.available": "Une mise a jour est disponible.\n\nInstallee : {current}\nDerniere : {latest}",
    "updates.open_release": "Ouvrir la release",
}

STRINGS["es"] = dict(STRINGS["en"]) | {
    "group.installs": "Instalaciones",
    "group.workflow": "Flujo",
    "group.main_actions": "Flujo Principal",
    "group.filters": "Filtros",
    "group.dll_analysis": "Analisis DLL",
    "group.project": "Estado del Proyecto",
    "group.progress": "Progreso de Traduccion",
    "label.source_install": "Juego actual / juego con mod",
    "label.target_install": "Instalacion de referencia / juego de comparacion",
    "label.source_language": "Idioma de origen",
    "label.target_language": "Idioma de destino",
    "btn.browse": "Buscar...",
    "btn.load_source": "Cargar juego",
    "btn.compare": "Comparar con referencia",
    "btn.import_exchange": "Importar traduccion",
    "btn.apply_target": "Aplicar traducciones",
    "menu.file": "Archivo",
    "menu.view": "Ver",
    "menu.settings": "Configuracion",
    "menu.help": "Ayuda",
    "menuitem.project_load": "Cargar proyecto...",
    "menuitem.project_new": "Nuevo proyecto",
    "menuitem.project_save": "Guardar proyecto...",
    "menuitem.open_terminology": "Abrir terminologia...",
    "menuitem.check_updates": "Buscar actualizaciones...",
    "menuitem.about": "Acerca de",
    "status.language_changed": "Idioma cambiado.",
    "updates.title": "Actualizaciones",
    "updates.up_to_date": "FL Lingo esta actualizado. Version instalada: {version}",
    "updates.available": "Hay una actualizacion disponible.\n\nInstalada: {current}\nUltima: {latest}",
    "updates.open_release": "Abrir release",
}

STRINGS["ru"] = dict(STRINGS["en"]) | {
    "group.installs": "Ustanovki",
    "group.workflow": "Rabochiy protsess",
    "group.main_actions": "Osnovnoy protsess",
    "group.filters": "Filtry",
    "group.dll_analysis": "Analiz DLL",
    "group.project": "Status proekta",
    "group.progress": "Progress perevoda",
    "label.source_install": "Tekushchaya igra / igra s modom",
    "label.target_install": "Referensnaya ustanovka / igra dlya sravneniya",
    "label.source_language": "Yazyk istochnika",
    "label.target_language": "Tselevoy yazyk",
    "btn.browse": "Obzor...",
    "btn.load_source": "Zagruzit igru",
    "btn.compare": "Sravnit s etalonom",
    "btn.import_exchange": "Importirovat perevod",
    "btn.apply_target": "Primenit perevody",
    "menu.file": "Fail",
    "menu.view": "Vid",
    "menu.settings": "Nastroyki",
    "menu.help": "Pomoshch",
    "menuitem.project_load": "Zagruzit proekt...",
    "menuitem.project_new": "Novyy proekt",
    "menuitem.project_save": "Sohranit proekt...",
    "menuitem.open_terminology": "Otkryt terminologiyu...",
    "menuitem.check_updates": "Proverit obnovleniya...",
    "menuitem.about": "O programme",
    "status.language_changed": "Yazyk izmenen.",
    "updates.title": "Obnovleniya",
    "updates.up_to_date": "FL Lingo aktualen. Ustanovlennaya versiya: {version}",
    "updates.available": "Dostupno obnovlenie.\n\nUstanovleno: {current}\nNovaya versiya: {latest}",
    "updates.open_release": "Otkryt release",
}

STRINGS = load_ui_translations(STRINGS)
